/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SnailPot Studio (https://sketchfab.com/snailpot_studio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-red-among-us-imposter-b13f848036194a38901852396e8f91b1
title: Simple Red Among Us IMPOSTER
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/amongus/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.PolySphere_PolySphere_0.geometry} material={materials.PolySphere} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/amongus/scene.gltf')
