/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shubhanshu Soni (https://sketchfab.com/sonishubhanshu99)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-37249acae18b406d8c1c160d7c0bc8e6
title: Earth
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations, Stage } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth/scene.gltf')
  const { actions,ref,mixer } = useAnimations(animations, group)

  useEffect(() => void mixer.clipAction(animations[5], ref.current).play(),
  [mixer, animations, ref])


  return (
    
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Earth" rotation={[-Math.PI / 2, 0, -1.54]} scale={[99.31, 99.31, 99.31]}>
            <mesh geometry={nodes.Earth_Earth_0.geometry} material={materials.Earth} />
          </group>
          <group name="Clouds" rotation={[-Math.PI / 2, 0, 0]} scale={99}>
            <mesh geometry={nodes.Clouds_Clouds_0.geometry} material={materials.Clouds} />
          </group>
          <group position={[3157.23, 104.21, 2142.97]} rotation={[-Math.PI, 0.82, -3.12]} scale={[100, 100, 100]} />
          <group position={[-436.27, -42, -2270.24]} rotation={[-0.71, 0.68, -0.72]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth/scene.gltf')
